FROM php:7.4.5-fpm

RUN apt-get update && apt-get install -y libpq-dev git zip unzip && apt-get clean

RUN pecl install mongodb && \
	docker-php-ext-enable mongodb

RUN docker-php-ext-install pdo pdo_mysql pdo_pgsql

RUN curl -sS https://getcomposer.org/installer -o composer-setup.php && \
	php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
	rm composer-setup.php

COPY ./ /var/www/app

WORKDIR /var/www/app

RUN composer install