version: "3"

services:
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    user: "1000:1000"

  nginx:
    image: nginx:1.14.0
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/app/web

  apache2:
    image: httpd:2.4.43
    ports:
      - 88:80
    volumes:
      - ./docker/apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./web:/var/www/app/web

  redis:
    image: redis:4.0.9
    volumes:
      - redis-data:/data
    command: '--appendonly yes'

  mongo:
    image: mongo:3.6.3
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:10.12
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  mysql:
    image: mysql:5.7.29
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password

volumes:
  redis-data:
  mongo-data:
  pg-data:
  mysql-data: