version: "3"

services:
  nginx:
    image: vudav/docker-course:nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile_build
    ports:
      - 80:80

  apache:
    image: vudav/docker-course:apache
    build:
      context: .
      dockerfile: ./docker/apache2/Dockerfile_build
    ports:
      - 88:80

  php:
    image: vudav/docker-course:php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile_build